# To speed up local development, this additional config will
# prevent Jekyll from copying icons unless specified (which
# should match what's listed in .gitignore).
#
# Add this flag to `bundle exec jekyll serve`:
# --config _config.yml,_config-local.yml
#
# This is only necessary if USWDS has been compiled locally. It prevents
# each build from copying 2K+ assets to _site. Otherwise (as with CI/CD)
# the site will build only from the committed icons.
#
# Jekyll 4 is required. Jekyll 3 will not copy icons with this config,
# as `include` is a v4 config option.

exclude:
  - assets/uswds/img/favicons
  - assets/uswds/img/material-icons
  - assets/uswds/img/material-icons-deprecated
  - assets/uswds/img/usa-icons/*
  - assets/uswds/img/usa-icons-bg/*
  - assets/uswds/img/uswds-icons/*

include:
  - assets/uswds/img/usa-icons/close.svg
  - assets/uswds/img/usa-icons/facebook.svg
  - assets/uswds/img/usa-icons/twitter.svg
  - assets/uswds/img/usa-icons/instagram.svg
  - assets/uswds/img/usa-icons/youtube.svg
  - assets/uswds/img/usa-icons/rss_feed.svg
  - assets/uswds/img/usa-icons/expand_more.svg
  - assets/uswds/img/usa-icons/expand_less.svg
  - assets/uswds/img/usa-icons-bg/search--white.svg
